version: "3.9"

services:

  beauty_web:
    build: .
    restart: unless-stopped
    command: >
      bash -c "python manage.py wait_db &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8003 --workers ${GUNICORN_WORKERS} --threads ${GUNICORN_THREADS}"
    expose:
      - 8003
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - beauty_postgres
    links:
      - beauty_postgres

  beauty_postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  beauty_nginx:
    restart: unless-stopped
    image: nginx:stable
    expose:
      - 8002
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - beauty_web
    labels:
      - "traefik.enable=true"
      - "traefik.subdomain=fastapi"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8002"
      - "traefik.http.routers.fastapi.tls.certresolver=letsEncrypt"

  redis:
    image: "redis:latest"
    restart: unless-stopped
    expose:
      - 6379

  beauty_celery_main:
    build: .
    command: celery -A config worker -l INFO
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - beauty_postgres
      - redis
      - beauty_web


networks:
  default:
    name: traefik
    external: true
