version: "3.3"

services:

  web:
    build: .
    restart: unless-stopped
    command: >
      bash -c "python manage.py wait_db &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py load_fixtures &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS} --threads ${GUNICORN_THREADS}"
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  nginx:
    restart: unless-stopped
    image: nginx:stable
    expose:
      - 8002
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.beauty.loadbalancer.server.port=8002"
      - "traefik.http.routers.beauty.rule=Host(`${DOMAIN}`) && Path(`/beauty`)"
      - "traefik.http.routers.beauty.tls.certresolver=letsEncrypt"


networks:
  default:
    external:
      name: traefik
