# Generated by Django 4.1.2 on 2023-01-19 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(related_name='specialists', to='service.servicecategory', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='salonimg',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_imgs', to='salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='sale',
            name='salons',
            field=models.ManyToManyField(related_name='sales', to='salon.salon', verbose_name='Салоны'),
        ),
        migrations.AddField(
            model_name='review',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_reviews', to='salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='review',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_reviews', to='salon.specialist', verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_orders', to='salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='service.servicecategory', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_orders', to='salon.specialist', verbose_name='Cпециалист'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon', verbose_name='Для клиентов салона'),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_users',
            field=models.ManyToManyField(related_name='personal_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Для конкретных клиентов'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.ManyToManyField(related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messenger',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_messengers', to='salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='messenger',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.messengertype', verbose_name='Тип мессенджера'),
        ),
    ]
