# Generated by Django 4.1.2 on 2023-01-18 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='notification',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon'),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_users',
            field=models.ManyToManyField(related_name='personal_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
