# Generated by Django 4.1.2 on 2023-01-19 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0003_alter_order_options_notification_for_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_all',
            field=models.BooleanField(default=True, verbose_name='Для всех клиентов компании'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='for_salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon', verbose_name='Для клиентов салона'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='for_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='personal_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Для конкретных клиентов'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
