# Generated by Django 4.1.2 on 2023-01-22 06:45

import apps.auth_app.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_faq_messengertype_is_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=70, verbose_name='Текст блока')),
                ('text', models.CharField(max_length=128, verbose_name='Текст блока')),
                ('promo', models.CharField(max_length=15, verbose_name='Промо')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Секция мобильного приложения',
                'verbose_name_plural': 'Секции мобильного приложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'FAQ'},
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('img', models.FileField(upload_to='app_stores', validators=[apps.auth_app.validators.validate_image_and_svg_file_extension], verbose_name='Изображение ')),
                ('link', models.CharField(max_length=512, verbose_name='Ссылка')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='salon.mobileappsection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Магазин приложений',
                'verbose_name_plural': 'Магазины приложений',
                'ordering': ['-created_at'],
            },
        ),
    ]
