# Generated by Django 4.1.2 on 2023-01-24 06:59

import apps.auth_app.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_mobileappsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-updated_at'], 'verbose_name': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='mobileappsection',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Секция мобильного приложения', 'verbose_name_plural': 'Секция мобильного приложения'},
        ),
        migrations.CreateModel(
            name='AppReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('img', models.FileField(upload_to='app_stores', validators=[apps.auth_app.validators.validate_image_and_svg_file_extension], verbose_name='Изображение ')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='salon.mobileappsection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Магазин приложений',
                'verbose_name_plural': 'Магазины приложений',
                'ordering': ['-updated_at'],
            },
        ),
    ]
