# Generated by Django 4.1.2 on 2023-01-26 04:06

import apps.auth_app.validators
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_alter_faq_options_alter_mobileappsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo_black',
            field=models.FileField(blank=True, null=True, upload_to='company', validators=[apps.auth_app.validators.validate_image_and_svg_file_extension], verbose_name='Логотип темный'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='work_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='salon',
            name='work_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.FileField(upload_to='company', validators=[apps.auth_app.validators.validate_image_and_svg_file_extension], verbose_name='Логотип cветлый'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
