# Generated by Django 4.1.2 on 2023-01-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_addserviceimg'),
        ('salon', '0007_companyinfo_logo_black_companyinfo_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappsection',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='site', verbose_name='Изображение для секции приложения'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='specialists', to='service.servicecategory', verbose_name='Услуги'),
        ),
    ]
