# Generated by Django 4.1.2 on 2023-01-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_mobileappsection_img_alter_specialist_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappsection',
            name='img_for_section',
            field=models.ImageField(blank=True, null=True, upload_to='site', verbose_name='Изображение для секции приложения'),
        ),
        migrations.AlterField(
            model_name='mobileappsection',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='site', verbose_name='Изображение для страницы приложения'),
        ),
    ]
