# Generated by Django 4.1.2 on 2023-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_salon_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='coords',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Координаты(58.786093,62.516021)'),
        ),
    ]
