# Generated by Django 4.1.2 on 2023-02-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_salon_coords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appreasons',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Причина для установки приложения', 'verbose_name_plural': 'Причины для установки приложения'},
        ),
        migrations.AlterField(
            model_name='appreasons',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='salon.mobileappsection', verbose_name='Секция'),
        ),
    ]
