# Generated by Django 4.1.2 on 2023-02-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_confinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Текст'),
        ),
    ]
