# Generated by Django 4.1.2 on 2023-02-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_notification_title_alter_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreasons',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appreasons',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='confinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='confinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='messengertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='messengertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='mobileappsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mobileappsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='salonimg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='salonimg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='workimg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='workimg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
    ]
