# Generated by Django 4.1.2 on 2023-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_alter_appreasons_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_img',
            field=models.ImageField(blank=True, null=True, upload_to='company', verbose_name='Доп изображение для сайта'),
        ),
    ]
