# Generated by Django 4.1.2 on 2023-02-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0016_companyinfo_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(default='app', max_length=10, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='button_text',
            field=models.CharField(help_text='Максимальная длина 29 символов', max_length=29, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='desc',
            field=models.CharField(help_text='Максимальная длина 128 символов', max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='text',
            field=models.TextField(help_text='Максимальная длина 512 символов', max_length=512, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(help_text='Максимальная длина 64 символа', max_length=64, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='TgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('token', models.CharField(max_length=128, null=True, verbose_name='Токен бота ТГ')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salon.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Телеграмм бота',
                'verbose_name_plural': 'Телеграмм боты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatsIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=128, verbose_name='Имя пользователя')),
                ('chat_id', models.PositiveIntegerField(verbose_name='ID чата')),
                ('tg_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='salon.tgsettings')),
            ],
            options={
                'verbose_name': 'Пользователь ТГ',
                'verbose_name_plural': 'Пользователи ТГ',
                'ordering': ['name'],
            },
        ),
    ]
