# Generated by Django 4.1.2 on 2023-03-08 04:28

import apps.auth_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0018_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('head', models.TextField(blank=True, help_text='Добавить общим html', null=True, verbose_name='Добавление в Head')),
                ('body', models.TextField(blank=True, help_text='Добавить общим html', null=True, verbose_name='Добавление в Body')),
            ],
            options={
                'verbose_name': 'CEO скрипт',
                'verbose_name_plural': 'CEO скрипты',
            },
        ),
        migrations.AlterField(
            model_name='appreasons',
            name='img',
            field=models.FileField(help_text='Рекомендуемый размер 56px в формате SVG', upload_to='app_stores', validators=[apps.auth_app.validators.validate_image_and_svg_file_extension], verbose_name='Изображение '),
        ),
        migrations.AlterField(
            model_name='appreasons',
            name='title',
            field=models.CharField(help_text='Максимально 64 символа', max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_img',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер 1200Х325px', null=True, upload_to='company', verbose_name='Доп изображение для сайта'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='img',
            field=models.ImageField(help_text='Рекомендуемый размер 1600Х100px', upload_to='company', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='img',
            field=models.ImageField(help_text='Рекомендуемый размер 600Х320px', upload_to='sales', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='salonimg',
            name='img',
            field=models.ImageField(help_text='Рекомендуемый размер: главная - 1200Х480px, остальные - 700Х480px', upload_to='salons', verbose_name='Изображение салона'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(help_text='Рекомендуемый формат вертикальный (9:16) с шириной не более 520px', upload_to='specialists', verbose_name='Фото'),
        ),
    ]
