# Generated by Django 4.1.2 on 2023-03-22 02:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_ceo_alter_appreasons_img_alter_appreasons_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
    ]
