# Generated by Django 4.1.2 on 2023-04-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0021_script_alter_ceo_options_remove_ceo_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('script', models.TextField(blank=True, help_text='Добавить без тега script', null=True, verbose_name='Скрипт')),
            ],
            options={
                'verbose_name': 'Скрипт для body',
                'verbose_name_plural': 'Скрипты для body',
            },
        ),
        migrations.CreateModel(
            name='HeadScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('script', models.TextField(blank=True, help_text='Добавить без тега script', null=True, verbose_name='Скрипт')),
            ],
            options={
                'verbose_name': 'Скрипт для head',
                'verbose_name_plural': 'Скрипты для head',
            },
        ),
        migrations.RemoveField(
            model_name='ceo',
            name='body_scripts',
        ),
        migrations.RemoveField(
            model_name='ceo',
            name='head_scripts',
        ),
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.AddField(
            model_name='headscript',
            name='ceo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.ceo', verbose_name='head_scripts'),
        ),
        migrations.AddField(
            model_name='bodyscript',
            name='ceo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.ceo', verbose_name='body_scripts'),
        ),
    ]
