# Generated by Django 4.1.2 on 2023-04-19 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0022_bodyscript_headscript_remove_ceo_body_scripts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='work_time',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_time',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='work_time_end',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Время окончания работы'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='work_time_start',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Время начала работы'),
        ),
    ]
