# Generated by Django 4.1.2 on 2023-04-19 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('salon', '0023_remove_companyinfo_work_time_remove_salon_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='segments',
            field=models.ManyToManyField(related_name='orders', to='schedule.plannedsegment'),
        ),
        migrations.AddField(
            model_name='salon',
            name='work_time_end',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Время окончания работы'),
        ),
        migrations.AddField(
            model_name='salon',
            name='work_time_start',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Время начала работы'),
        ),
        migrations.AlterField(
            model_name='bodyscript',
            name='ceo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_scripts', to='salon.ceo'),
        ),
        migrations.AlterField(
            model_name='headscript',
            name='ceo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_scripts', to='salon.ceo'),
        ),
    ]
