# Generated by Django 4.1.2 on 2023-04-19 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0024_order_segments_salon_work_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='segments',
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 19, 13, 52, 11, 69431), verbose_name='Время окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 19, 13, 52, 46, 557447), verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
    ]
