# Generated by Django 4.1.2 on 2023-04-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0026_order_planned_segments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('app', 'Приложение'), ('site', 'Сайт'), ('admin', 'Администратор')], default='admin', max_length=10, verbose_name='Источник'),
        ),
    ]
