# Generated by Django 4.1.2 on 2023-03-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_addserviceimg_img_alter_servicecategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Cоздается автоматически', max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
