# Generated by Django 4.1.2 on 2023-03-22 02:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_addserviceimg_img_alter_servicecategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
    ]
