# Generated by Django 4.1.2 on 2023-01-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon'),
        ),
    ]
