# Generated by Django 4.1.2 on 2023-04-19 07:02

import apps.auth_app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0023_remove_companyinfo_work_time_remove_salon_work_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[apps.auth_app.validators.validate_segment])),
                ('start_time', models.TimeField(verbose_name='Начало промежутка')),
                ('end_time', models.TimeField(verbose_name='Окончание промежутка')),
            ],
            options={
                'verbose_name': 'Промежуток времени',
                'verbose_name_plural': 'Промежутки времени',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_time_start', models.TimeField(verbose_name='Начало рабочего дня')),
                ('work_time_end', models.TimeField(verbose_name='Окончание рабочего дня')),
                ('break_time_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_time_end', models.TimeField(blank=True, null=True, verbose_name='Окончание перерыва')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='salon.salon')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='salon.specialist', verbose_name='Cпециалист')),
            ],
            options={
                'verbose_name': 'График работы специалиста',
                'verbose_name_plural': 'Графики работы специалистов',
                'ordering': ['-date'],
                'unique_together': {('spec', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlannedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_busy', models.BooleanField(default=False, verbose_name='Занят?')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_segments', to='schedule.segment')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_segments', to='salon.specialist', verbose_name='Cпециалист')),
            ],
            options={
                'verbose_name': 'Промежуток времени',
                'verbose_name_plural': 'Промежутки времени',
                'unique_together': {('spec', 'date', 'segment')},
            },
        ),
    ]
