# Generated by Django 4.1.2 on 2023-04-20 14:05

import apps.auth_app.validators
from django.db import migrations, models
import django.db.models.deletion
from apps.schedule import services


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0026_order_planned_segments_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedsegment',
            options={'verbose_name': 'Рабочий интервал', 'verbose_name_plural': 'Рабочие интервалы'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-date'], 'verbose_name': 'Дневной график работы специалиста', 'verbose_name_plural': 'Дневные графики работы специалистов'},
        ),
        migrations.AddField(
            model_name='plannedsegment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='plannedsegment',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_time_end',
            field=models.TimeField(blank=True, null=True, validators=[apps.auth_app.validators.validate_time], verbose_name='Окончание перерыва'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_time_start',
            field=models.TimeField(blank=True, null=True, validators=[apps.auth_app.validators.validate_time], verbose_name='Начало перерыва'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='salon.salon', verbose_name='Салон'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_time_end',
            field=models.TimeField(default=services.get_default_time_end, validators=[apps.auth_app.validators.validate_time], verbose_name='Окончание рабочего дня'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_time_start',
            field=models.TimeField(default=services.get_default_time_start, validators=[apps.auth_app.validators.validate_time], verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end_time',
            field=models.TimeField(validators=[apps.auth_app.validators.validate_time], verbose_name='Окончание промежутка'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_time',
            field=models.TimeField(validators=[apps.auth_app.validators.validate_time], verbose_name='Начало промежутка'),
        ),
    ]
