# Generated by Django 4.1.2 on 2023-04-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0027_alter_order_source'),
        ('schedule', '0002_alter_plannedsegment_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='plannedsegment',
            name='is_busy',
        ),
        migrations.AlterField(
            model_name='plannedsegment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_planned_segments', to='salon.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='salon.salon', verbose_name='Салон'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('spec', 'date', 'salon')},
        ),
    ]
